# Generated by Django 5.2.8 on 2025-12-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='visited',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
