# Generated by Django 5.2.8 on 2025-12-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellog', '0002_destination_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
