# Generated by Django 5.2.8 on 2025-12-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travellog', '0003_destination_latitude_destination_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
